import Link from "next/link";
import { notFound } from "next/navigation";
import PageLayout from "@/components/PageLayout";
import { getMatchInsights, getUpcomingGameweekMatches, getUpcomingMatches } from "@/lib/football-api";
import type { MatchInsights, MatchResult } from "@/lib/types";

function FormResults({ results }: { results: MatchResult[] }) {
  if (results.length === 0) return <span className="text-xs text-gray-400">Not available</span>;
  return (
    <div className="flex flex-wrap gap-1.5">
      {results.map((result, index) => (
        <span key={`${result.date}-${index}`} title={`${result.date}: ${result.score} vs ${result.opponent}`} className={`flex h-6 w-6 items-center justify-center rounded text-xs font-bold ${result.outcome === "W" ? "bg-green-100 text-green-700" : result.outcome === "D" ? "bg-yellow-100 text-yellow-700" : "bg-red-100 text-red-700"}`}>
          {result.outcome}
        </span>
      ))}
    </div>
  );
}

function freshnessLabel(fetchedAt: string): string {
  const age = Math.max(0, Date.now() - new Date(fetchedAt).getTime());
  const minutes = Math.floor(age / 60000);
  if (minutes < 1) return "Updated just now";
  if (minutes < 60) return `Updated ${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  return `Updated ${hours}h ago`;
}

function MatchInsightsPanel({ insights }: { insights: MatchInsights | null }) {
  if (!insights) return null;
  const hasData = insights.recentForm.some((item) => item.results.length) || insights.headToHead.length || insights.injuries.length || insights.lineups.length;
  if (!hasData) return null;
  return (
    <section className="mt-6 rounded border border-gray-200 bg-white p-4">
      <div className="flex items-center justify-between gap-3">
        <h2 className="text-sm font-bold uppercase text-gray-700">Match insights</h2>
        <span className="text-right text-[10px] text-gray-400">API-Football · cached<br />{freshnessLabel(insights.fetchedAt)}</span>
      </div>
      {insights.aiBriefing && (
        <div className="mt-4 rounded border border-emerald-100 bg-emerald-50 p-3">
          <div className="flex items-center justify-between gap-3">
            <h3 className="text-xs font-bold uppercase text-emerald-800">AI match briefing</h3>
            <span className="text-[10px] font-semibold text-emerald-700">{insights.aiBriefing.angle} · {insights.aiBriefing.confidence} confidence</span>
          </div>
          <p className="mt-1 text-sm text-emerald-900">{insights.aiBriefing.summary}</p>
          <p className="mt-2 text-[10px] text-emerald-700">Generated by DeepSeek from the available match data. Not a guarantee.</p>
        </div>
      )}
      <div className="mt-4 grid gap-4 md:grid-cols-2">
        <div>
          <h3 className="text-xs font-semibold text-gray-500">Recent form</h3>
          <div className="mt-2 space-y-2 text-sm text-gray-700">
            {insights.recentForm.map((item) => <div key={item.team} className="flex items-center justify-between gap-3"><span className="truncate">{item.team}</span><FormResults results={item.results} /></div>)}
          </div>
        </div>
        <div>
          <h3 className="text-xs font-semibold text-gray-500">Previous results</h3>
          {insights.headToHead.length ? <div className="mt-2 space-y-1 text-xs text-gray-600">{insights.headToHead.map((item, index) => <p key={`${item.date}-${index}`}>{item.date} · {item.score} · {item.opponent}</p>)}</div> : <p className="mt-2 text-xs text-gray-400">No head-to-head results available.</p>}
        </div>
      </div>
      <div className="mt-4 grid gap-4 border-t border-gray-100 pt-4 md:grid-cols-2">
        <div><h3 className="text-xs font-semibold text-gray-500">Injuries</h3>{insights.injuries.length ? <ul className="mt-2 space-y-1 text-xs text-gray-600">{insights.injuries.map((item, index) => <li key={`${item.player}-${index}`}>{item.player} ({item.team}){item.reason ? ` · ${item.reason}` : ""}</li>)}</ul> : <p className="mt-2 text-xs text-gray-400">No injury data reported.</p>}</div>
        <div><h3 className="text-xs font-semibold text-gray-500">Lineups</h3>{insights.lineups.length ? <div className="mt-2 space-y-1 text-xs text-gray-600">{insights.lineups.map((item) => <p key={item.team}>{item.team}: {item.formation || "formation unavailable"}{item.coach ? ` · ${item.coach}` : ""}</p>)}</div> : <p className="mt-2 text-xs text-gray-400">Lineups have not been published.</p>}</div>
      </div>
      {insights.quota?.remaining !== undefined && <p className="mt-4 text-[10px] text-gray-400">Provider quota remaining: {insights.quota.remaining}{insights.quota.limit ? ` / ${insights.quota.limit}` : ""}</p>}
    </section>
  );
}

export default async function MatchDetailPage({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ offset?: string; range?: string }>;
}) {
  const { id } = await params;
  const { offset: rawOffset, range } = await searchParams;
  const parsedOffset = Number(rawOffset || "0");
  const offset = Number.isInteger(parsedOffset)
    ? Math.max(-7, Math.min(14, parsedOffset))
    : 0;
  const matches = range === "week" ? await getUpcomingGameweekMatches(7) : await getUpcomingMatches(offset);
  const match = matches.find((m) => m.id === Number(id));

  if (!match) notFound();
  const insights = await getMatchInsights(match);

  return (
    <PageLayout>
      <div className="rounded bg-white p-6 shadow-sm">
        <p className="text-xs text-gray-500">{match.league} · {match.date ? `${match.date} · ` : ""}{match.time}</p>
        <h1 className="mt-2 text-2xl font-bold text-gray-800">
          {match.homeTeam} vs {match.awayTeam}
        </h1>

        <div className="mt-6 grid gap-4 sm:grid-cols-2">
          <div className="rounded border border-gray-200 p-4">
            <h2 className="text-xs font-bold uppercase text-gray-500">Free Tip</h2>
            {match.tip === "Stats soon" ? (
              <p className="mt-2 text-sm text-gray-600">
                A form signal is not available yet. The fixture and kickoff time are live from the public feed.
              </p>
            ) : match.tipType === "free" ? (
              <p className="mt-2 text-2xl font-bold text-brand-green">{match.tip}</p>
            ) : (
              <p className="mt-2 text-sm text-gray-600">
                This pick is available on our{" "}
                <Link href="/premium" className="font-semibold text-brand-green hover:underline">
                  Premium plan
                </Link>
                .
              </p>
            )}
          </div>
          <div className="rounded border border-gray-200 p-4">
            <h2 className="text-xs font-bold uppercase text-gray-500">Match Info</h2>
            <p className="mt-2 text-sm text-gray-600">Kickoff: {match.time} EAT</p>
            <p className="text-sm text-gray-600">Status: {match.status || "Scheduled"}</p>
          </div>
        </div>

        <div className="mt-6 rounded bg-gray-50 p-4 text-sm text-gray-600">
          {match.analysis && (
            <p className="mb-3 rounded border-l-4 border-brand-green bg-green-50 px-3 py-2 text-gray-700">
              <span className="font-semibold">Automated table-form signal:</span> {match.analysis}
            </p>
          )}
          <p>
            This indicator is calculated from current league-table performance and is not a guarantee.
            For the full analysis and combined odds, check our{" "}
            <Link href="/accumulators" className="text-brand-green hover:underline">accumulators</Link>{" "}
            or subscribe to{" "}
            <Link href="/premium" className="text-brand-green hover:underline">premium tips</Link>.
          </p>
        </div>
      </div>
      <MatchInsightsPanel insights={insights} />
    </PageLayout>
  );
}
